services:
  react_app:
    build:
      context: ./front-end/
      args:
        REACT_APP_USE_MOCK_API: ${REACT_APP_USE_MOCK_API}
        REACT_APP_ICE_CONFIGURATION: ${REACT_APP_ICE_CONFIGURATION}
    ports:
      - "8081:80"
    depends_on:
      - express_server
    restart: on-failure

  express_server:
    build: ./back-end/
    ports:
      - "8080:8080"
    environment:
      - DB_URI=mongodb://root:internalPW@mongo
      - ACCESS_TOKEN_TTL
      - REFRESH_TOKEN_TTL
      - PRIVATE_KEY
      - PUBLIC_KEY
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    image: mongo
    volumes:
      - mongo_medGenie:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: internalPW
    logging:
      driver: "none"

volumes:
  mongo_medGenie:
