name: Selenium Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
        chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
      - name: Grant execute permission for maven
        run: chmod +x mvn # give permission to mvn to run the commands
      - name: Build with Maven
        run: |
          cd tests/selenium/
          mvn --batch-mode --update-snapshots verify
          mvn test