name: Build & test Back-end

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    env:
      ACCESS_TOKEN_TTL: 20m
      PRIVATE_KEY: "samplePrivateKeyForTesting"
      PUBLIC_KEY: "samplePublicKeyForTesting"
      REFRESH_TOKEN_TTL: 1y
      DB_URI: mongodb://root:example@localhost:27017
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd src/back-end/
          npm ci
          npm run build --if-present
          npm test
